#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$icons = (array) json_decode(file_get_contents(__DIR__ . '/icons.json'));

$path = '/src/icons/';
$import = [
	'import Vue from \'vue\'',
	'import OfcoldIcon from \'./Icon\'',
];
$viewBoxs = [];
$componetns = ['Vue.component(\'ofcold-icon\', OfcoldIcon)'];

$h = '';
foreach ($icons as $key => $val) {
	$h .= '<li class="ofcold-icon-item" data-name="' . $key . '" title="' . $key . '"><ofcold-icon :width="40" :height="40" type="' . $key . '"/> <div>' . $key . '</div></li>' . "\r\n";
	// $import[] = 'import Ofcold'. studly_case($key) .' from \'./icons/' . studly_case($key) . '\'';
	// $componetns[] .= 'Vue.component(\'ofcold-icon-' . $key . '\', Ofcold'. studly_case($key) .')';
	// $viewBoxs[$key] = '0 0 ' . $val['0'] . ' ' . $val[1];
	// file_put_contents(__DIR__ . $path . studly_case($key) . '.vue', '<template functional><path d="' . array_last($val) . '"/></template>');
}
file_put_contents(__DIR__ . '/html', $h);
// file_put_contents(__DIR__ . '/src/index.js', implode($import, "\r\n") . "\r\n\r\n" .  implode($componetns, "\r\n"));
// file_put_contents(__DIR__ . '/src/view-box.js', 'module.exports = ' . json_encode($viewBoxs));
